language: node_js
node_js:
  - v8
  - v7
script:
  - npm test
services:
  - postgresql
before_script:
  - psql -c 'create database evtsys_test;' -U postgres
env:
  global:
    - DB_PORT=5432
    - DB_HOST=127.0.0.1
    - DB_USERNAME=postgres
    - DB_PASSWORD=~
    - DB_NAME=evtsys_test
